### ISSUE TITLE
Missing file image-pairs.csv for downloading the dataset

### ISSUE THREAD

**Issue by gmberton** [seyrankhademi/AmsterTime#2]
Hi, many thanks for making the code public!
I tried to download the images using `download_data.ipynb`, but it complains that it doesn't find the file './data/image-pairs.csv'. Could you add it to the repo?
Also, it might be good to add a link to your paper in the readme :)

**Comment by byildiz** [comment]
Hi @gmberton,
The dataset can be downloaded at https://doi.org/10.4121/19580806 or https://www.kaggle.com/datasets/byildiz/amstertime.
