### ISSUE TITLE
Retrieval reproducibility

### ISSUE THREAD

**Issue by gmberton** [seyrankhademi/AmsterTime#3]
Hi, I downloaded the descriptors of the VGG-16 (vgg16_imagenet.p) and ran the retrieval task like this

`python -m ctd.eval --task retrieval --file tasks/retrieval.csv --feats 27962799`

The results look like this:

```Old
mAP 0.05848903330625508
Top1 0.05848903330625508
Top5 0
New
mAP 0.036555645816409424
Top1 0.036555645816409424
Top5 0
All
mAP 0.04752233956133225
Top1 0.04752233956133225
Top5 0
```
How can I obtain the results in the paper (Top1 0.13)?
Also, why is the Top5 always 0?

Thank you in advance

**Comment by MAX-OTW** [comment]
Hello, @byildiz ,I really appreciate for your work.I'm trying to reproduce results of the paper.But I met some difficulties.Here is my instruction:
`python -m amstertime.eval --task retrieval --file tasks/retrieval.csv --feats features/simsiam_resnet50_scratch_amstertime_ep10000_bs128.p --k 128 --dist_type cosine`

The result is:
`Old
mAP 0.18771090970011878
Top1 0.12022745735174654
Top5 0.25913891145410234
New
mAP 0.16641443668175546
Top1 0.11129163281884646
Top5 0.21039805036555642
All
mAP 0.17706267319093713
Top1 0.11575954508529651
Top5 0.23476848090982938
`
But the result in the paper is mAP:0.19;Top1:0.12;Top5:0.26.How to solve the problem?
In addition, I have sent you an email and look forward to receiving your reply as soon as possible.Thanks a lot!
Best regards.

**Comment by byildiz** [comment]
Hi @MAX-OTW ,
If you round the results of the queries as historical images (it is marked up with Old in your result text: `Old mAP 0.18771090970011878 Top1 0.12022745735174654 Top5 0.25913891145410234`) to 2 decimals the result is the same as the result given in the paper.

**Comment by MAX-OTW** [comment]
Hi，Burak Yildiz，
I'm reproducing your paper《 AmsterTime: A Visual Place Recognition
Benchmark Dataset for Severe Domain Shift 》,many thanks for making the code
public! My current research interests are deep learning and self-supervised
learning，the method of this article is worth my learning and I'd like to
learn more from you.

You know,there will inevitably be some problems in the process of
reproducing the paper, so I want to keep timely communication with you.I
come from China.Do you have any social media accounts?(something like LinkedIn
and so on) that I can further chat with you and learn from you~

I hope to get your reply as soon as possible. Thank you very much!

Thanks & Best Regards!

Yours sincerely,
               Yang

Burak Yildiz ***@***.***> 于2022年8月27日周六 23:14写道：

**Comment by MAX-OTW** [comment]
@byildiz
